spring:
  datasource:
    todos:
      url: jdbc:mysql://localhost:3306/bookstoredb?useCursorFetch=true&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 1234
      driverClassName: com.mysql.cj.jdbc.Driver
      hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
    topics:
      url: jdbc:postgresql://localhost:5432/ehrpayroll_db
      username: postgres
      password: 1234
      driverClassName: org.postgresql.Driver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  #drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
#    database: POSTGRESQL #Exception:  Unknown table 'SEQUENCES' in information_schema
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
          batch_size: 10000
      generate_statistics: true
      order_inserts: true



#####################################################################
#spring:
#  datasource:
#    sourceType: CDP
#    url: jdbc:oracle:thin:@//localhost:2999/pisrat.dpdbfront1.oal.oraclevcn.com
#    driver-class-name: oracle.jdbc.OracleDriver
#    username: oalg2m_consumption
#    password: bfwaD#g2m_oBj
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimumIdle: 1
#      maximumPoolSize: 50
#      idleTimeout: 30000
#      connectionTimeout: 30000
#      maxLifeTime: 600000